import { renderTrack, renderTrackUri, type TrackNote } from './synth'

/**
 * The one loop, built out of arithmetic like everything else this game plays.
 *
 * **Rule: this file never imports `phaser`** — covered by `npm run verify:audio`.
 *
 * ## ⚠ This is the FALLBACK now, and the file it fell back from came back
 *
 * `AUDIO-SOURCES.md` says the rule plainly: **CC0 or self-generated, nothing else**, because an
 * unresolved copyright claim on a sound is one of the most common Playables rejections. A 2.76MB
 * mp3 sat in that registry with no source and no licence, and was on its own the reason
 * `npm run build` was red — 8.07MB against an 8MB working ceiling. It went out and this file
 * replaced it.
 *
 * **What brought a recording back is a fact, not a change of rule**: the tracks are *generated*
 * (Stable Audio), which is self-generated by the same argument these tones are. So `Preloader`
 * loads `audio/music.mp3` and renders this loop only when that file does not arrive — which is a
 * case worth covering rather than a formality, because `playMusic` calls `soundManager.add(key)`
 * and that throws on a key the cache does not hold: a missing music file would take the front
 * screen with it, not merely silence it.
 *
 * It is therefore live code with a live caller, and `verify:audio` asserts both halves — that the
 * file is what is loaded, and that this is what stands behind it. If the licence question ever
 * returns, the fallback becomes the track again by changing one line in `Preloader`.
 *
 * ## What a waveform cannot do, and what it turns out it can
 *
 * The comment this replaces read: *"a loop is the one thing a waveform cannot be"*. That is true of
 * `renderSamples`, which renders **one tone**, and it stopped being true the moment `renderTrack`
 * existed — a loop is not a different kind of sound, it is a schedule of the same kind. What a
 * waveform still cannot be is a *recording*: this is a chiptune bed and it is not pretending to be
 * the orchestral thing that was there before. That is a real loss and it is the price of the rule.
 *
 * ## The tune
 *
 * Eight bars of I–V–vi–IV in C, at 112bpm — the most ordinary cheerful progression there is, which
 * is what a background bed for an endless runner should be. Four voices, and each earns its place
 * by doing something the others cannot:
 *
 * - **the bass** is the only voice below 200Hz, so it is what survives a phone speaker's rolloff —
 *   the same measurement that picked the coin and the impact (see `AUDIO-SOURCES.md`);
 * - **the chord arpeggio** is what makes the progression audible at all; a bass line alone reads as
 *   a pulse rather than as harmony;
 * - **the melody** is the only voice that changes between the two halves, which is what stops eight
 *   bars reading as four played twice;
 * - **the hats** are the only noise in the track, and they are what carries the tempo when the
 *   melody rests.
 *
 * **⚠ It is quiet on purpose.** Every gain here is a fraction of what an SFX carries: the loop plays
 * under the whole game and the sounds that matter — a coin, a close pass, a hit — have to cut
 * through it. `verify:audio` measures the peak against the loudest one-shot rather than trusting
 * that.
 */

/** The one music track's key, under which `audio.ts` retains a single instance. */
export const MUSIC_KEY = 'music'

/**
 * Tempo and length.
 *
 * **Eight bars rather than four, and it costs 378k samples.** Four bars of I–V–vi–IV is 8.6 seconds
 * and the ear finds the seam inside a minute — the same objection the sun's two incommensurate
 * breathing periods were chosen against, arriving in the one place a period genuinely is fixed. What
 * eight buys is that the melody differs between the halves, so what repeats is the *harmony* and not
 * the tune.
 */
export const MUSIC = {
  bpm: 112,
  bars: 8,
  beatsPerBar: 4,
} as const

/** One bar in milliseconds, and the whole loop. */
export const MUSIC_BEAT_MS = 60000 / MUSIC.bpm
export const MUSIC_BAR_MS = MUSIC_BEAT_MS * MUSIC.beatsPerBar
export const MUSIC_LENGTH_MS = MUSIC_BAR_MS * MUSIC.bars

/** Equal temperament from A4, so a note is written as a name rather than as a frequency. */
const A4 = 440
const SEMITONE_OF: Record<string, number> = { C: -9, D: -7, E: -5, F: -4, G: -2, A: 0, B: 2 }

export function noteHz(name: string): number {
  const step = SEMITONE_OF[name[0]]
  const octave = Number(name[name.length - 1])
  const sharp = name.includes('#') ? 1 : 0

  return A4 * Math.pow(2, (step + sharp + (octave - 4) * 12) / 12)
}

/**
 * The progression, one chord per bar. Two rounds of I–V–vi–IV.
 *
 * Written as note names because that is what it is: transposing the whole track is an edit to this
 * table and to nothing else, where a table of frequencies would be eight numbers to recompute.
 */
const CHORDS: readonly (readonly string[])[] = [
  ['C3', 'E4', 'G4', 'C5'],
  ['G2', 'D4', 'G4', 'B4'],
  ['A2', 'E4', 'A4', 'C5'],
  ['F2', 'C4', 'F4', 'A4'],
  ['C3', 'E4', 'G4', 'C5'],
  ['G2', 'D4', 'G4', 'B4'],
  ['A2', 'E4', 'A4', 'C5'],
  ['F2', 'C4', 'F4', 'A4'],
]

/**
 * The melody, as a note per half-beat and `null` for a rest — one row per four bars.
 *
 * **The second half is deliberately not the first.** Eight bars whose melody repeated at bar five
 * would be a four-bar loop wearing a longer one's clothes, which is exactly what the length was
 * spent to avoid.
 */
const MELODY: readonly (string | null)[] = [
  // bars 1-4: the statement
  'G4', null, 'E4', null, 'G4', 'A4', 'G4', null,
  'D4', null, 'B3', null, 'D4', 'G4', 'D4', null,
  'E4', null, 'C4', null, 'E4', 'G4', 'A4', null,
  'F4', null, 'A4', null, 'C5', null, 'A4', null,
  // bars 5-8: the answer, higher and busier
  'C5', 'B4', 'G4', null, 'C5', 'D5', 'E5', null,
  'D5', null, 'B4', 'D5', 'G4', null, 'B4', null,
  'A4', 'C5', 'E5', null, 'C5', 'B4', 'A4', null,
  'F4', 'A4', 'C5', 'A4', 'G4', null, 'E4', null,
]

/**
 * Every voice in the loop, as scheduled tones.
 *
 * Built rather than typed out: the bass, the arpeggio and the hats are all a function of the bar
 * they are in, and writing 8 bars x 4 voices by hand is 128 rows nobody could re-tune.
 */
export function musicNotes(): TrackNote[] {
  const notes: TrackNote[] = []
  const half = MUSIC_BEAT_MS / 2

  for (let bar = 0; bar < MUSIC.bars; bar++) {
    const chord = CHORDS[bar % CHORDS.length]
    const barAt = bar * MUSIC_BAR_MS

    // The bass: the root on beats one and three, long and low. A triangle rather than a sine
    // because a sine at 65Hz is felt and not heard on the speaker most of this game is played on.
    for (const beat of [0, 2]) {
      notes.push({
        atMs: barAt + beat * MUSIC_BEAT_MS,
        tone: {
          waveform: 'triangle',
          frequency: noteHz(chord[0]),
          durationMs: MUSIC_BEAT_MS * 1.7,
          attackMs: 8,
          releaseMs: MUSIC_BEAT_MS * 0.9,
          gain: 0.3,
        },
      })
    }

    // The arpeggio: the chord's upper three, one per beat, climbing then falling back. Short, so
    // the harmony is stated rather than sustained under the melody.
    const shape = [1, 2, 3, 2]

    for (let beat = 0; beat < MUSIC.beatsPerBar; beat++) {
      notes.push({
        atMs: barAt + beat * MUSIC_BEAT_MS,
        tone: {
          waveform: 'triangle',
          frequency: noteHz(chord[shape[beat]]),
          durationMs: MUSIC_BEAT_MS * 0.7,
          attackMs: 6,
          releaseMs: MUSIC_BEAT_MS * 0.5,
          gain: 0.11,
        },
      })
    }

    // The hats: one per half-beat, alternating loud and quiet so the bar has a pulse rather than a
    // tick. The only noise in the track.
    for (let step = 0; step < MUSIC.beatsPerBar * 2; step++) {
      notes.push({
        atMs: barAt + step * half,
        tone: {
          waveform: 'noise',
          frequency: 8000,
          durationMs: step % 2 === 0 ? 34 : 22,
          attackMs: 1,
          releaseMs: step % 2 === 0 ? 30 : 20,
          gain: step % 2 === 0 ? 0.055 : 0.03,
        },
      })
    }
  }

  // The melody, over the whole eight bars. A square at low gain: it is the one voice that has to be
  // picked out of the bed, and a square is what does that without being loud.
  MELODY.forEach((name, step) => {
    if (!name) return

    notes.push({
      atMs: step * half,
      tone: {
        waveform: 'square',
        frequency: noteHz(name),
        durationMs: half * 0.85,
        attackMs: 5,
        releaseMs: half * 0.6,
        gain: 0.075,
      },
    })
  })

  return notes
}

/**
 * The whole loop as mono float samples.
 *
 * **At `SAMPLE_RATE` rather than at a lower music-only rate**, and that is forced rather than
 * chosen: `renderSamples` renders every tone at that constant, so a track assembled at any other
 * rate would play every note at the wrong pitch. Giving the renderer a rate argument would be the
 * way to make an 11kHz music bed possible, and it is not worth a change to the one function every
 * sound in the game goes through to save half a megabyte of memory that never reaches `dist/`.
 */
export function renderMusic(): Float32Array {
  return renderTrack(musicNotes(), MUSIC_LENGTH_MS)
}

/** The whole loop as a `data:` URI, for `Preloader` to hand the ordinary loader. */
export function renderMusicUri(): string {
  return renderTrackUri(musicNotes(), MUSIC_LENGTH_MS)
}
