/**
 * Renders the game's sound effects as WAV bytes, at boot, from a description.
 *
 * **Rule: this file never imports `phaser`** — covered by `npm run verify:audio`.
 *
 * **Why generate rather than ship files.** Every audio file in this project needs a row in
 * `AUDIO-SOURCES.md` establishing that it is CC0 or self-generated, because an unresolved
 * copyright claim on a sound is one of the commonest Playables rejections. A tone rendered
 * here is self-generated by construction — there is no provenance question to answer, nothing
 * to license, and nothing in `dist/`. It also costs no bundle weight: the whole set is a few
 * hundred lines of arithmetic producing ~40KB of PCM that never touches the network.
 *
 * The output is a `data:` URI, not an `AudioBuffer`, so it goes through Phaser's ordinary
 * loader and works on **both** sound backends. Decoding straight to an `AudioBuffer` would be
 * shorter and would silently produce nothing at all under the HTML5 Audio fallback.
 */

/** Sample rate. 22050 is plenty for short blips and halves the bytes of 44100. */
export const SAMPLE_RATE = 22050

/**
 * Margin between the end of a volume ramp and destroying the node that was ramping, in ms.
 *
 * **Chromium silently drops a scheduled `AudioParam` change if the node is torn down in the
 * same tick** — no exception, no console warning, the sound simply cuts where it should have
 * faded. The observable edge is around 10ms; this is a deliberate margin past it. Anything that
 * mutes *and* tears down together is exposed: a scene change, a pause, the end of a run.
 *
 * Lives here, in the `phaser`-free half, purely so `teardownDelayMs` can be held to it by
 * `npm run verify:audio` — the number is the whole fix, and a silent failure is exactly the
 * kind that gets "tidied" back to zero by someone who cannot hear it break.
 */
export const FADE_TEARDOWN_GAP_MS = 40

/** When a sound that is fading over `fadeMs` may safely be destroyed. */
export function teardownDelayMs(fadeMs: number): number {
  return Math.max(0, fadeMs) + FADE_TEARDOWN_GAP_MS
}

export type Waveform = 'sine' | 'square' | 'triangle' | 'saw' | 'noise'

export interface ToneSpec {
  waveform: Waveform
  /** Starting frequency in Hz. Ignored for `'noise'`. */
  frequency: number
  /** Frequency at the end of the sound, for a sweep. Defaults to `frequency`. */
  sweepTo?: number
  durationMs: number
  /** Fade in and fade out, in milliseconds. */
  attackMs?: number
  releaseMs?: number
  /** Peak amplitude, `0..1`. */
  gain?: number
  /** Optional second voice a fixed number of semitones above the first, at half gain. */
  harmonicSemitones?: number
}

/** One sample of `waveform` at phase `t` (in cycles), plus a deterministic noise source. */
function sample(waveform: Waveform, phase: number, noise: () => number): number {
  switch (waveform) {
    case 'sine':
      return Math.sin(phase * Math.PI * 2)
    case 'square':
      return phase % 1 < 0.5 ? 1 : -1
    case 'triangle':
      return 4 * Math.abs(((phase + 0.75) % 1) - 0.5) - 1
    case 'saw':
      return 2 * (phase % 1) - 1
    case 'noise':
      return noise()
  }
}

/**
 * A tiny deterministic noise source.
 *
 * Deterministic for the same reason scenery and waves are: the sounds must be byte-identical
 * between two boots, or a "did the audio change?" question can never be answered by comparison.
 */
function createNoise(seed: number): () => number {
  let state = seed >>> 0

  return () => {
    state = (state * 1664525 + 1013904223) >>> 0

    return (state / 2147483648) - 1
  }
}

/** Renders a tone to mono float samples in `-1..1`. */
export function renderSamples(spec: ToneSpec): Float32Array {
  const count = Math.max(1, Math.round((spec.durationMs / 1000) * SAMPLE_RATE))
  const out = new Float32Array(count)
  const noise = createNoise(0x9e3779b9)
  const attack = Math.max(1, Math.round(((spec.attackMs ?? 4) / 1000) * SAMPLE_RATE))
  const release = Math.max(1, Math.round(((spec.releaseMs ?? spec.durationMs * 0.6) / 1000) * SAMPLE_RATE))
  const gain = spec.gain ?? 0.5
  const sweepTo = spec.sweepTo ?? spec.frequency
  const harmonic = spec.harmonicSemitones === undefined ? null : Math.pow(2, spec.harmonicSemitones / 12)

  let phase = 0
  let harmonicPhase = 0

  for (let i = 0; i < count; i++) {
    const t = i / count
    // Frequency is integrated into phase rather than recomputed from `i`, or a sweep would
    // produce a discontinuity every time the frequency changed.
    const frequency = spec.frequency + (sweepTo - spec.frequency) * t

    phase += frequency / SAMPLE_RATE
    if (harmonic !== null) harmonicPhase += (frequency * harmonic) / SAMPLE_RATE

    // Linear attack and release, which is all a 100ms blip needs and cannot click.
    const envelope = Math.min(1, i / attack, Math.max(0, count - i) / release)
    let value = sample(spec.waveform, phase, noise)

    if (harmonic !== null) value += 0.5 * sample(spec.waveform, harmonicPhase, noise)

    out[i] = Math.max(-1, Math.min(1, value * envelope * gain))
  }

  return out
}

/** Wraps mono float samples in a 16-bit PCM WAV container. */
export function encodeWav(samples: Float32Array, sampleRate: number = SAMPLE_RATE): Uint8Array {
  const dataBytes = samples.length * 2
  const buffer = new Uint8Array(44 + dataBytes)
  const view = new DataView(buffer.buffer)
  const ascii = (offset: number, text: string) => {
    for (let i = 0; i < text.length; i++) buffer[offset + i] = text.charCodeAt(i)
  }

  ascii(0, 'RIFF')
  view.setUint32(4, 36 + dataBytes, true)
  ascii(8, 'WAVE')
  ascii(12, 'fmt ')
  view.setUint32(16, 16, true) // PCM chunk size
  view.setUint16(20, 1, true) // format: PCM
  view.setUint16(22, 1, true) // channels: mono
  view.setUint32(24, sampleRate, true)
  view.setUint32(28, sampleRate * 2, true) // byte rate
  view.setUint16(32, 2, true) // block align
  view.setUint16(34, 16, true) // bits per sample
  ascii(36, 'data')
  view.setUint32(40, dataBytes, true)

  for (let i = 0; i < samples.length; i++) {
    const clamped = Math.max(-1, Math.min(1, samples[i]))

    // Asymmetric on purpose: signed 16-bit runs -32768..32767, and scaling both directions by
    // 32768 would clip the positive peak by one LSB on every full-scale sample.
    view.setInt16(44 + i * 2, clamped < 0 ? clamped * 0x8000 : clamped * 0x7fff, true)
  }

  return buffer
}

/** Base64 for a byte array, without pulling in a dependency or a Buffer polyfill. */
export function toBase64(bytes: Uint8Array): string {
  const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
  let out = ''

  for (let i = 0; i < bytes.length; i += 3) {
    const a = bytes[i]
    const b = i + 1 < bytes.length ? bytes[i + 1] : 0
    const c = i + 2 < bytes.length ? bytes[i + 2] : 0
    const triple = (a << 16) | (b << 8) | c

    out += alphabet[(triple >> 18) & 63]
    out += alphabet[(triple >> 12) & 63]
    out += i + 1 < bytes.length ? alphabet[(triple >> 6) & 63] : '='
    out += i + 2 < bytes.length ? alphabet[triple & 63] : '='
  }

  return out
}

/** Renders one tone all the way to a `data:` URI Phaser's loader can take. */
export function renderToneUri(spec: ToneSpec): string {
  return `data:audio/wav;base64,${toBase64(encodeWav(renderSamples(spec)))}`
}
